### ISSUE TITLE
Probeer images altijd width en height attributen mee te geven

### ISSUE THREAD

**Issue by KrijnHoetmer** [mcphendriks/connect-your-tribe-profile-card#2]
Lost 1 van de grootste performance issues op: https://web.dev/top-cwv-2023/

https://github.com/mcphendriks/connect-your-tribe-profile-card/blob/22c774cdbc63f562fb6b26ab00a3e2676d665b32/views/index.ejs#L6

**Comment by mcphendriks** [comment]
De width en height  attribute heb ik uitgeschreven in de <img> tag.  om de laadtijd te versnellen. Dit komt omdat de  lay-out van de pagina zich niet hoeft aan te passen en opnieuw hoeft te renderen. Dus, wanneer de witdth en height attributen wordt uitgeschreven in de CSS, moet de browser eerst wachten tot tot de CSS is geanalyseerd voordat hij weet welke afmetingen en afbeelding heeft.

Bron: https://web.dev/top-cwv-2023/
