### ISSUE TITLE
Formatting document

### ISSUE THREAD

**Issue by TessaViergever** [mcphendriks/connect-your-tribe-profile-card#4]
Hola! Ik zag dat een aantal elementen op dezelfde lijn staan, wellicht netter om html te formatten (bijv. met prettier of evt. handmatig)? 

https://github.com/mcphendriks/connect-your-tribe-profile-card/blob/22c774cdbc63f562fb6b26ab00a3e2676d665b32/views/index.ejs#L47

**Comment by mcphendriks** [comment]
Yes did it :)
