### ISSUE TITLE
Is dit alt attribuut wat je bedoelt?

### ISSUE THREAD

**Issue by KrijnHoetmer** [mcphendriks/connect-your-tribe-profile-card#6]
Dit wordt nu voorgelezen als "/"..

https://github.com/mcphendriks/connect-your-tribe-profile-card/blob/22c774cdbc63f562fb6b26ab00a3e2676d665b32/views/index.ejs#L6

**Comment by mcphendriks** [comment]
Issue opgelost en de alt text "Michelle smiles in front of a cool shop in London" uitgeschreven. De alt-tekst is uitgeschreven, zodat de gebruikers van screen reader dezelfde 'betekenis' van de pagina krijgt als een goedziende gebruiker.

Bron: https://jakearchibald.com/2021/great-alt-text/
