### ISSUE TITLE
Pas op met harde waardes in je CSS :)

### ISSUE THREAD

**Issue by KrijnHoetmer** [mcphendriks/connect-your-tribe-profile-card#7]
Zie ook https://polypane.app/blog/responsive-design-ground-rules/#rule-6-avoid-fixed-dimensions

https://github.com/mcphendriks/connect-your-tribe-profile-card/blob/22c774cdbc63f562fb6b26ab00a3e2676d665b32/public/styles/style.css#L32-L33

**Comment by mcphendriks** [comment]
Ik heb gebruik gemaakt van de Property "padding ". Dit omdat ik geen vaste container hoogte nodig heb, maar de container responsive wil maken. 

Bron: https://polypane.app/blog/responsive-design-ground-rules/#rule-6-avoid-fixed-dimensions
